// Generated by CoffeeScript 1.3.3

jQuery(function() {
  var navLayout;
  navLayout = function() {
    if ($('body').width() < 480) {
      $('header .btn').show();
      $('#nav').addClass('collapse');
    } else {
      $('.posts-link').hide();
      $('header .btn').hide();
      $('.collapse').removeClass('in collapse').css('height', '');
      $('.brand').show();
    }
  };
  navLayout();
  $('header .btn').click(function() {
    $('.brand').hide();
    $('.posts-link').show();
    $('header .btn').hide();
  });
  $(window).resize(function() {
    navLayout();
  });
});
